siiuttlax/apps/reporte_tutoria/urls.py
from django.urls import path
from . import views

app_name = "reporte_tutoria"
urlpatterns = [
    path('', views.reporte_tutoria, name='reporte_tutorias'),
    path('success/', views.success_view, name='success'),
    path('mis_reportes/', views.mis_reportes, name='mis_reportes'),
    path('canalizacion_alumno', views.canalizacion_alumno, name='canalizacion_alumno'),
    path('canalizacion_exitosa/', views.canalizacion_exitosa, name='canalizacion_exitosa')
]

siiuttlax/siiuttlax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Importaciones de las vistas personalizadas
from apps.justify.views import CustomLoginView, alumno_view, tutor_view, revisar_justificante_view
from apps.cumplimiento.views import index, consultas_por_periodo

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.user_profile.urls')),
    path('', include('apps.academy.urls')),
    path('', include('apps.interview.urls')),
    path('', include('apps.testvak.urls')),
    path('', include('apps.group.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('consulta', index, name='index'),
    path('consultas/<int:periodo_id>/', consultas_por_periodo, name='consultas_por_periodo'),
    path('seguimiento/',include('apps.seguimiento.urls')),
    path('reporte_tutoria/', include('apps.reporte_tutoria.urls', namespace='reporte_tutoria')),
    path('seguimiento/', include('apps.seguimiento.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('solicitar/', alumno_view, name='ruta_alumno'),
    path('revisar/', tutor_view, name='ruta_tutor'),
    path('revisar/justificante/<int:justificante_id>/', revisar_justificante_view, name='ruta_para_revisar_justificante'),
    path('vocational/', include('apps.vocational.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siiuttlax/apps/reporte_tutoria/models.py
from django.db import models
from apps.career.models import Career
from apps.period.models import Semester
from apps.group.models import Group
from apps.academy.models import Professor, Student

class ReporteTutoria(models.Model):
    fecha_tutoria = models.DateField(verbose_name='Fecha de Tutoría')
    carrera = models.ForeignKey(Career, on_delete=models.CASCADE, verbose_name='Carrera')
    semestre = models.ForeignKey(Semester, on_delete=models.CASCADE, verbose_name='Semestre')
    grupo = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='Grupo')
    nombre_actividad = models.CharField(max_length=255, verbose_name='Nombre de la Actividad')
    objetivo_actividad = models.TextField(verbose_name='Objetivo de la Actividad')
    descripcion_actividad = models.TextField(verbose_name='Descripción de la Actividad')
    evidencia_fotografica = models.FileField(upload_to='evidencias/imagenes_videos', verbose_name='Evidencia fotografica', blank=False, null=False)
    evidencia_lista_asistencia = models.FileField(upload_to='evidencias/pdf', verbose_name='Evidencia list_asistencia', blank=False, null=False)
    evidencia_audio = models.FileField(upload_to='evidencias/audio', verbose_name='Evidencia de audio', blank=False, null=False)
    tutor = models.ForeignKey(Professor, on_delete=models.CASCADE, verbose_name='Tutor')

    def __str__(self):
        return f'Reporte de Tutoría {self.fecha_tutoria} - {self.tutor}'

    class Meta:
        verbose_name = 'Reporte de Tutoría'
        verbose_name_plural = 'Reportes de Tutorías'
        ordering = ['-fecha_tutoria']

class CanalizacionAlumno(models.Model):
    fecha_creacion = models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')
    carrera = models.ForeignKey(Career, on_delete=models.CASCADE, verbose_name='Carrera')
    semestre = models.ForeignKey(Semester, on_delete=models.CASCADE, verbose_name='Semestre')
    grupo = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='Grupo')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='Estudiante')
    evidencia_canalizacion_alumno = models.FileField(upload_to='evidencias/pdf_canalizacion', verbose_name='Evidencia pdf_canalizacion', blank=False, null=False)
    tutor = models.ForeignKey(Professor, on_delete=models.CASCADE, verbose_name='Tutor')

    def __str__(self):
        return f'Canalización del Alumno {self.fecha_creacion} - {self.student}'

    class Meta:
        verbose_name = 'Canalización del Alumno'
        verbose_name_plural = 'Canalizaciones de Alumnos'
        ordering = ['-fecha_creacion']

siiuttlax/apps/reporte_tutoria/views.py
from django.contrib.auth.decorators import login_required
from datetime import date, datetime
from django.shortcuts import render, redirect
from django.contrib import messages
from apps.career.models import Career
from apps.period.models import Semester
from apps.group.models import Group
from apps.academy.models import Professor, Student
from apps.interview.models import InitialInterview
from .models import ReporteTutoria, CanalizacionAlumno
from django.http import HttpResponseForbidden

def reporte_tutoria(request):
    # Obtener la fecha actual
    fecha_actual = datetime.now()

    # Calcular el mes y año del reporte
    mes_reporte = fecha_actual.month - 1 if fecha_actual.month > 1 else 12
    año_reporte = fecha_actual.year if fecha_actual.month > 1 else fecha_actual.year - 1

    # Verificar si estamos en los primeros 5 días del mes siguiente
    if not (1 <= fecha_actual.day <= 5):
        return HttpResponseForbidden("No puedes acceder a este módulo fuera del período permitido.")

    # Si la fecha es válida, continuar con el proceso del reporte
    if request.method == 'POST':
        fecha_tutoria = request.POST.get('fecha')
        carrera_id = request.POST.get('carrera')
        semestre_id = request.POST.get('semestre')
        grupo_id = request.POST.get('grupo')
        nombre_actividad = request.POST.get('nombre_actividad')
        objetivo_actividad = request.POST.get('objetivo_actividad')
        descripcion_actividad = request.POST.get('descripcion_actividad')
        evidencia_fotografica = request.FILES.get('evidencia_fotografica')
        evidencia_lista_asistencia = request.FILES.get('evidencia_lista_asistencia')
        evidencia_audio = request.FILES.get('evidencia_audio')
      

        if not (fecha_tutoria and nombre_actividad and objetivo_actividad and descripcion_actividad and evidencia_fotografica and evidencia_lista_asistencia):
            messages.error(request, 'Por favor, complete todos los campos requeridos.')
            return redirect('reporte_tutoria:reporte_tutorias')

       
        reporte = ReporteTutoria(
            fecha_tutoria = fecha_tutoria,
            carrera_id = carrera_id,
            semestre_id = semestre_id,
            grupo_id = grupo_id,
            nombre_actividad = nombre_actividad,
            objetivo_actividad = objetivo_actividad,
            descripcion_actividad = descripcion_actividad,
            evidencia_fotografica = evidencia_fotografica,
            evidencia_lista_asistencia = evidencia_lista_asistencia,
            evidencia_audio = evidencia_audio,
            tutor = request.user.professor    
        )
        reporte.save()

        # Redirigir a una página de éxito o a donde necesites después de guardar
        return redirect('reporte_tutoria:success') 

    else:
        tutor = request.user.professor  
        group = tutor.group_set.first()  # Obtener el primer grupo del tutor
        carrera = group.career
        semestre = group.semester

        context = {
            'reporte': { 
                'carreras': Career.objects.all(), 
                'semestres': Semester.objects.all(),  
                'grupos': Group.objects.all(),
            },
            'default_carrera': carrera.id,
            'default_semestre': semestre.id,
            'default_grupo': group.id,
        }
        return render(request, 'reporte_tutorias/reporte_tutoria.html', context)
    
def success_view(request):
    return render(request, 'reporte_tutorias/success.html')

@login_required
def mis_reportes(request):
    reportes = ReporteTutoria.objects.filter(tutor=request.user.professor).order_by('-fecha_tutoria', 'nombre_actividad')
    return render(request, 'reporte_tutorias/mis_reportes.html', {'reportes': reportes})


@login_required
def canalizacion_alumno(request):
    tutor = request.user.professor
    group = tutor.group_set.first()  # Obtener el primer grupo del tutor

    if not group:
        messages.error(request, 'No tiene ningún grupo asignado.')
        return render(request, 'reporte_tutorias/canalizacion_alumno.html', {
            'canalizacion': {
                'carreras': [],
                'semestres': [],
                'grupos': [],
            },
            'default_carrera': None,
            'default_semestre': None,
            'default_grupo': None,
            'students': []
        })

    carrera = group.career
    semestre = group.semester

    # Obtener los estudiantes relacionados con el grupo del tutor
    interviews = InitialInterview.objects.filter(grupo_escolar=group)
    students = [interview.student for interview in interviews if interview.student]

    if request.method == 'POST':
        carrera_id = request.POST.get('carrera')
        semestre_id = request.POST.get('semestre')
        grupo_id = request.POST.get('grupo')
        student_id = request.POST.get('student')  # Obtener el estudiante seleccionado del formulario
        evidencia_canalizacion_alumno = request.FILES.get('evidencia_canalizacion_alumno')

        if not (evidencia_canalizacion_alumno):
            messages.error(request, 'Por favor, complete todos los campos requeridos.')
            return redirect('reporte_tutoria:canalizacion_alumno')

        # Crear la instancia de CanalizacionAlumno
        canalizacion = CanalizacionAlumno(
            carrera_id = carrera_id,
            semestre_id = semestre_id,
            grupo_id = grupo_id,
            student_id = student_id,  # Asignar el estudiante seleccionado
            evidencia_canalizacion_alumno = evidencia_canalizacion_alumno,
            tutor = tutor
        )
        canalizacion.save()

        # Redirigir o mostrar mensaje de éxito
        messages.success(request, 'Canalización del alumno registrada exitosamente.')
        return redirect('reporte_tutoria:canalizacion_exitosa') 

    context = {
        'canalizacion': {
            'carreras': Career.objects.all(),
            'semestres': Semester.objects.all(),
            'grupos': Group.objects.all(),
        },
        'default_carrera': carrera.id,
        'default_semestre': semestre.id,
        'default_grupo': group.id,
        'students': students  # Pasar los estudiantes al contexto
    }
    return render(request, 'reporte_tutorias/canalizacion_alumno.html', context)

def canalizacion_exitosa(request):
    return render(request, 'reporte_tutorias/canalizacion_exitosa.html')

siiuttlax/templates/reporte_tutorias/canalizacion_alumno.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@200&family=Comfortaa:wght@300;400;500&family=Didact+Gothic&family=Nova+Square&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/canalizacion_alumno.css' %}"/>
    <title>Tutorías | {% block title %}{% endblock %}</title>
    <script>
        function validateForm() {
            let evidencia4 = document.getElementById("evidencia4").value;

            if (!evidencia4 ) {
                alert("Por favor, complete todos los campos requeridos.");
                return false;
            }
            return true;
        }
    </script>
</head>
<body>
    <nav>
        <div class="logo">
            <img src="{% static 'img/logoUTT.png' %}" alt="Logo"/>
            <h1>Sistema Integral de Tutorías</h1>
        </div>

        <ul class="navigation">
            <li><a href="{% url 'home' %}">Inicio</a></li>
            <li>
                <a href="#">
                    UTT
                    <i class='bx bxs-chevron-down js-arrow'></i>
                </a>
                <div class="subnavigation__wrapper">
                    <ul>
                        <li><a href="#">Página UTT</a></li>
                        <li><a href="#">EVAUTT</a></li>
                        <li><a href="#">SAIIUTT</a></li>
                    </ul>
                </div> 
            {% if user.is_authenticated %}
                <li>
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn">Cerrar sesión</button>
                    </form>
                </li>
            {% else %}
                <li><a href="{% url 'login' %}" class="btn">Iniciar sesión</a></li>
            {% endif %}
        </ul>
    </nav>

    
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h1>Canalización del Alumno</h1>
            </div>
            <div class="card-body">
                <form method="post" action="" enctype="multipart/form-data" onsubmit="return validateForm();">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="carrera">Carrera:</label>
                        <select id="carrera" disabled>
                            <option value="">Seleccione una carrera</option>
                            {% for carrera in canalizacion.carreras %}
                                <option value="{{ carrera.id }}" {% if carrera.id == default_carrera %} selected {% endif %}>{{ carrera.short_name }}</option>
                            {% endfor %}
                        </select>
                        <input type="hidden" name="carrera" value="{{ default_carrera }}">
                    </div>
                    <div class="form-group">
                        <label for="semestre">Cuatrimestre:</label>
                        <select id="semestre" disabled>
                            <option value="">Selecciona el Cuatrimestre</option>
                            {% for cuatrimestre in canalizacion.semestres %}
                                <option value="{{ cuatrimestre.id }}" {% if cuatrimestre.id == default_semestre %} selected {% endif %}>{{ cuatrimestre.semester }}</option>
                            {% endfor %}
                        </select>
                        <input type="hidden" name="semestre" value="{{ default_semestre }}">
                    </div>
                    <div class="form-group">
                        <label for="grupo">Grupo:</label>
                        <select id="grupo" disabled>
                            <option value="">Selecciona el grupo</option>
                            {% for grupo in canalizacion.grupos %}
                                <option value="{{ grupo.id }}" {% if grupo.id == default_grupo %} selected {% endif %}>{{ grupo.group }}</option>
                            {% endfor %}
                        </select>
                        <input type="hidden" name="grupo" value="{{ default_grupo }}">
                    </div>
                    <div class="form-group">
                        <label for="student">Estudiante:</label>
                        <select id="student" name="student" required>
                            <option value="">Seleccione un estudiante</option>
                            {% for student in students %}
                                <option value="{{ student.id }}">{{ student.full_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="evidencia4" class="file-label">Evidencia PDF del alumno canalizado:</label>
                        <input type="file" id="evidencia4" name="evidencia_canalizacion_alumno" accept=".pdf" title="Selecciona evidencia adicional">
                    </div>
                    <button type="submit" class="btn-submit" title="Enviar">Enviar</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

siiuttlax/templates/reporte_tutorias/canalizacion_exitosa.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/canalizacion_exitosa.css' %}"/>
    <title>Éxito</title>
</head>
<body>
    <h1>Canalizacion de alumno enviado con éxito</h1>
    <p>La canalizacion del Alumno ha sido enviada correctamente.</p>
    <div class="links-container">
        <ul>
            <li><a href="{% url 'home' %}">Regresar al Inicio</a></li>
        </ul>
    </div>
</body>
</html>

siiuttlax/templates/reporte_tutorias/mis_reportes.html
{% load static %}
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>
    <link
        href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@200&family=Comfortaa:wght@300;400;500&family=Didact+Gothic&family=Nova+Square&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/mis_reportes.css' %}"/>
</head>
<body>
    <nav>
        <div class="logo">
            <img src="{% static 'img/logoUTT.png' %}" alt="Logo"/>
            <h1>Sistema Integral de Tutorías</h1>
        </div>
    
        <ul class="navigation">
            <li><a href="{% url 'home' %}">Inicio</a></li>
            
            <li>
                <a href="#">
                    UTT
                    <i class='bx bxs-chevron-down js-arrow'></i>
                </a>
                <div class="subnavigation__wrapper">
                    <ul>
                        <li><a href="#">Página UTT</a></li>
                        <li><a href="#">EVAUTT</a></li>
                        <li><a href="#">SAIIUTT</a></li>
                    </ul>
                </div>
            </li>
                 <a href="{% url 'reporte_tutoria:reporte_tutorias' %}">Reporte de Tutoria</a>
            </li>
            {% if user.is_authenticated %}
                <li>
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn">Cerrar sesión</button>
                    </form>
                </li>
            {% else %}
                <li><a href="{% url 'login' %}" class="btn">Iniciar sesión</a></li>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
        <h1>Mis Reportes de Tutoría</h1>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Fecha de Tutoria</th>
                    <th>Nombre de la Actividad de Tutoría</th>
                    <th>Objetivo de la Actividad de Tutoría</th>
                </tr>
            </thead>
            <tbody>
                {% for reporte in reportes %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ reporte.fecha_tutoria }}</td>
                    <td>{{ reporte.nombre_actividad }}</td>
                    <td>{{ reporte.objetivo_actividad }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2">No tienes reportes de tutoría registrados.</td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>  
</body>
</html>

siiuttlax/templates/reporte_tutorias/reporte_tutoria.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@200&family=Comfortaa:wght@300;400;500&family=Didact+Gothic&family=Nova+Square&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/reporte_tutoria.css' %}"/>
    <title>Tutorías | {% block title %}{% endblock %}</title>
    <script>
        function validateForm() {
            let fecha = document.getElementById("fecha").value;
            let nombreActividad = document.getElementById("nombre_actividad").value;
            let objetivoActividad = document.getElementById("objetivo_actividad").value;
            let descripcionActividad = document.getElementById("descripcion_actividad").value;
            let evidencia1 = document.getElementById("evidencia1").value;
            let evidencia2 = document.getElementById("evidencia2").value;

            if (!fecha || !nombreActividad || !objetivoActividad || !descripcionActividad || !evidencia1 || !evidencia2 || !evidencia3) {
                alert("Por favor, complete todos los campos requeridos.");
                return false;
            }
            return true;
        }
    </script>
</head>
<body>
    <nav>
        <div class="logo">
            <img src="{% static 'img/logoUTT.png' %}" alt="Logo"/>
            <h1>Sistema Integral de Tutorías</h1>
        </div>

        <ul class="navigation">
            <li><a href="{% url 'home' %}">Inicio</a></li>
            <li>
                <a href="#">
                    UTT
                    <i class='bx bxs-chevron-down js-arrow'></i>
                </a>
                <div class="subnavigation__wrapper">
                    <ul>
                        <li><a href="#">Página UTT</a></li>
                        <li><a href="#">EVAUTT</a></li>
                        <li><a href="#">SAIIUTT</a></li>
                    </ul>
                </div>
            </li>
                  <a href="{% url 'reporte_tutoria:mis_reportes' %}">Reportes de Tutoria</a>
            </li>
            
            {% if user.is_authenticated %}
                <li>
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn">Cerrar sesión</button>
                    </form>
                </li>
            {% else %}
                <li><a href="{% url 'login' %}" class="btn">Iniciar sesión</a></li>
            {% endif %}
        </ul>
    </nav>

    <div class="hoja">
        <header>
            <img src="{% static 'img/Encabezado.jpg' %}" alt="Encabezado">
        </header>
        <div class="encabezado">
            <h1>REPORTE DE TUTORIA</h1>
            <br>
            <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    <label for="fecha">Fecha de Tutoria:</label>
                    <input type="date" id="fecha" name="fecha" value="{{ fecha_tutoria|date:"Y-m-d" }}" title="Fecha de Tutoria">
                </div>
                <div>
                    <label for="carrera">Carrera:</label>
                    <select id="carrera" disabled>
                        <option value="">Seleccione una carrera</option>
                        {% for carrera in reporte.carreras %}
                            <option value="{{ carrera.id }}" {% if carrera.id == default_carrera %} selected {% endif %}>{{ carrera.short_name }}</option>
                        {% endfor %}
                    </select>
                    <input type="hidden" name="carrera" value="{{ default_carrera }}">
                </div>
                <br>
                <div>
                    <label for="semestre">Cuatrimestre:</label>
                    <select id="semestre" disabled>
                        <option value="">Selecciona el Cuatrimestre</option>
                        {% for cuatrimestre in reporte.semestres %}
                            <option value="{{ cuatrimestre.id }}" {% if cuatrimestre.id == default_semestre %} selected {% endif %}>{{ cuatrimestre.semester }}</option>
                        {% endfor %}
                    </select>
                    <input type="hidden" name="semestre" value="{{ default_semestre }}">
                </div>
                <br>
                <div>
                    <label for="grupo">Grupo:</label>
                    <select id="grupo" disabled>
                        <option value="">Selecciona el grupo</option>
                        {% for grupo in reporte.grupos %}
                            <option value="{{ grupo.id }}" {% if grupo.id == default_grupo %} selected {% endif %}>{{ grupo.group }}</option>
                        {% endfor %}
                    </select>
                    <input type="hidden" name="grupo" value="{{ default_grupo }}">
                </div>
                <br>
                <div>
                    <label for="nombre_actividad">Nombre de la Actividad:</label>
                    <input type="text" id="nombre_actividad" name="nombre_actividad" placeholder="Nombre de la actividad" title="Nombre de la Actividad">
                </div>

                <div>
                    <label for="objetivo_actividad">Objetivo de la Actividad:</label>
                    <textarea id="objetivo_actividad" name="objetivo_actividad" rows="4" placeholder="Objetivo de la actividad" title="Objetivo de la Actividad"></textarea>
                </div>

                <div>
                    <label for="descripcion_actividad">Descripción de la Actividad:</label>
                    <textarea id="descripcion_actividad" name="descripcion_actividad" rows="6" placeholder="Descripción de la actividad" title="Descripción de la Actividad"></textarea>
                </div>

                <div class="evidencia-container">
                    <div>
                        <label for="evidencia1" class="file-label">Evidencia de Imagen/Video:</label>
                        <input type="file" id="evidencia1" name="evidencia_fotografica" accept=".png, .jpg, .jpeg, .mp4" title="Selecciona evidencia" data-description="Sube una imagen o un video.">
                    </div>
                    <div>
                        <label for="evidencia2" class="file-label">Evidencia PDF lista de asistencia:</label>
                        <input type="file" id="evidencia2" name="evidencia_lista_asistencia" accept=".pdf" title="Selecciona evidencia adicional" data-description="Sube un archivo PDF.">
                    </div>
                    <div>
                        <label for="evidencia3" class="file-label">Evidencia de Audio lista de asistencia:</label>
                        <input type="file" id="evidencia3" name="evidencia_audio" accept=".mp3" title="Selecciona evidencia adicional" data-description="Sube un archivo de audio en formato MP3.">
                    </div>
                </div>

                <br>
                <button type="submit" title="Enviar">Enviar</button>
                </form> 
                <br>
            </form>
        </div>
        <br>

        <footer>
            <img src="{% static 'img/Footer.jpg' %}" alt="Pie de página">
        </footer>
    </div>
</body>
</html>

siiuttlax/templates/reporte_tutorias/reporte_tutorias.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>REPORTE DE TUTORIAS</title>
    <link rel="stylesheet" href="/siiuttlax/static/css/styles.css">
</head>
<body>
    <div class="hoja">
        <header>
            <img src="/siiuttlax/static/img/Encabezado.jpg" alt="Encabezado">
        </header>
        
        <div class="encabezado">
            <h1>REPORTE DE TUTORIA</h1>
            <br>

            <p>Fecha de Tutoria:</p>
            <input type="date" value="" readonly>

            <p>Carrera:</p>
            <input type="text" value="" readonly>

            <p>Grado:</p>
            <input type="text" value="" readonly>

            <p>Grupo:</p>
            <input type="text" value="" readonly>

            <br>
            <p>Nombre de la Actividad:</p>
            <input type="text">

            <br>
            <p>Objetivo de la Actividad:</p>
            <textarea rows="4"></textarea>

            <br>
            <p>Descripción de la Actividad:</p>
            <textarea rows="6"></textarea>

            <br>
            <p>Evidencias </p>
            <input type="file" accept=".png, .jpg, .jpeg, .mp4">

            <br>
            <input type="file" accept=".pdf, .mp3">
        </div>

        <footer>
            <img src="/siiuttlax/static/img//Footer.jpg" alt="Pie de página">
        </footer>
    </div>
</body>
</html>

siiuttlax/templates/reporte_tutorias/success.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Éxito</title>
</head>
<body>
    <h1>Reporte guardado con éxito</h1>
    <p>Su reporte de tutoría ha sido guardado correctamente.</p>
    <a href="{% url 'home' %}"><button type="button">Regresar</button></a>
</body>
</html>