siiuttlax/apps/reporte_tutoria/urls.py
from django.urls import path
from . import views

app_name = "reporte_tutoria"
urlpatterns = [
    path('', views.reporte_tutoria, name='reporte_tutorias'),
    path('success/', views.success_view, name='success'),
    path('mis_reportes/', views.mis_reportes, name='mis_reportes'),
    path('canalizacion_alumno', views.canalizacion_alumno, name='canalizacion_alumno'),
    path('canalizacion_exitosa/', views.canalizacion_exitosa, name='canalizacion_exitosa')
]

siiuttlax/siiuttlax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Importaciones de las vistas personalizadas
from apps.justify.views import CustomLoginView, alumno_view, tutor_view, revisar_justificante_view
from apps.cumplimiento.views import index, consultas_por_periodo

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.user_profile.urls')),
    path('', include('apps.academy.urls')),
    path('', include('apps.interview.urls')),
    path('', include('apps.testvak.urls')),
    path('', include('apps.group.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('consulta', index, name='index'),
    path('consultas/<int:periodo_id>/', consultas_por_periodo, name='consultas_por_periodo'),
    path('seguimiento/',include('apps.seguimiento.urls')),
    path('reporte_tutoria/', include('apps.reporte_tutoria.urls', namespace='reporte_tutoria')),
    path('seguimiento/', include('apps.seguimiento.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('solicitar/', alumno_view, name='ruta_alumno'),
    path('revisar/', tutor_view, name='ruta_tutor'),
    path('revisar/justificante/<int:justificante_id>/', revisar_justificante_view, name='ruta_para_revisar_justificante'),
    path('vocational/', include('apps.vocational.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siiuttlax/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@200&family=Comfortaa:wght@300;400;500&family=Didact+Gothic&family=Nova+Square&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/cumplimiento.css' %}">
    <title>Tutorias | {% block title %}{% endblock %}</title>
</head>
<body>
    <nav>
        <div class="logo">
            <img src="{% static 'img/logoUTT.png'%}" alt="Logo"/>
            <h1>Sistema Integral de Tutorías</h1>
        </div>

        <ul class="navigation">
            <li><a href="{% url 'home' %}">Inicio</a></li>
            <li>
                <a href="#">
                    UTT
                    <i class='bx bxs-chevron-down js-arrow'></i>
                </a>
                <div class="subnavigation__wrapper">
                    <ul>
                        <li>
                            <a href="#">
                                Página UTT
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                EVAUTT
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                SAIIUTT
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <a href="#">
                    Tutoría
                    <i class='bx bxs-chevron-down js-arrow'></i>
                </a>
                <div class="subnavigation__wrapper">
                    <ul>
                        <li>
                            <a href="justifying_student.html">
                                Justificantes Alumno
                            </a>
                        </li>
                        <li>
                            <a href="justifying_teacher.html">
                                Justificantes Tutores
                            </a>
                        </li>
                        <li>
                            <a href="justifying_principal.html">
                                Justificantes Director
                            </a>
                        </li>
                        <li>
                            <a href="individual_monitoring.html">
                                Seguimiento Individual
                            </a>
                        </li>
                        <li>
                            <a href="survey_leave.html">
                                Encuesta Causa de Baja
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Test Orientacion Vocacional
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'reporte_tutoria:reporte_tutorias' %}">
                                Reportes de Tutoria
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'reporte_tutoria:canalizacion_alumno' %}">
                                Canalizacion de alumno
                            </a>
                        </li>
                        {% if user.is_authenticated %}
                            {% if user_type == 'profesor' %}
                                <li><a href="{% url 'update_profile' %}">Actualizar Usuario</a></li>
                                <li><a href="{% url 'update_perfil' %}">Actualizar Perfil</a></li>
                                <li><a href="{% url 'students_list' %}">Lista de estudiantes</a></li>
                            {% elif user_type == 'estudiante' %}
                                <li><a href="{% url 'fill_initial_interview' %}">Llenar Entrevista Inicial</a></li>
                                <li><a href="{% url 'update_profile' %}">Actualizar Usuario</a></li>
                                <li><a href="{% url 'update_perfil' %}">Actualizar Perfil</a></li>
                            {% elif user_type == 'administrador' %}
                                <li><a href="{% url 'create_professor' %}">Administrar Profesor</a></li>
                                <li><a href="{% url 'manage_groups' %}">Administrar Grupo</a></li>
                            {% endif %}
                        {% endif %}
                    </ul>
                </div>
            </li>
            <li>
                <a href="#">
                    Servicios
                </a>
            </li>
            {% if user.is_authenticated %}

                <li>
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn">Cerrar sesión</button>
                    </form>
                </li>
            {% else %}
                <li><a href="{% url 'login' %}" class="btn">Iniciar sesión</a></li>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}    
    </div>
</body>
</html>